#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

exec >/dev/console 2>&1

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "develop" ]; then
  echo "You can't commit directly to develop branch\nPlease switch to another branch."
  exit 1
fi

if [ "$branch" = "main" ]; then
  echo "You can't commit directly to main branch\nPlease switch to another branch."
  exit 1
fi

npx lint-staged
